### ISSUE TITLE
Eukariotic phylums in TBDB

### ISSUE THREAD

**Issue by octolis** [mpiersonsmela/tbox#3]
I was very happy to find TBDB and appreciate the comprehensive annotation which helps a lot in my research. However, I found a strange thing: there are 'Ascomycota', 'Nematoda', 'Arthropoda' in "phylum" field. I believe it is a mistake as afaik T-boxes are not found in Eukarya. I blasted several sequences annotated with these phylums and have a strong suspicion that "eukaryotic" T-boxes were taken from the contaminated or unreliable genomes. Could you please comment on that?

**Comment by mpiersonsmela** [comment]
Yes, we also noticed this during construction of the database. It's likely that this represents bacterial contamination in genome assemblies although it is also possible (but less likely) for this to be horizontal gene transfer. 

In any case, if you wish to exclude these sequences you can easily filter them out since we annotated the phylum.
